# Generated by Django 4.2.4 on 2023-09-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_base', '0002_song_duration_alter_song_descriptions_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='descriptions',
            field=models.ManyToManyField(blank=True, related_name='songs', to='music_base.description'),
        ),
    ]
