# Generated by Django 4.2.4 on 2024-05-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_base', '0006_song_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(related_name='songs', to='music_base.tag'),
        ),
    ]
