# Generated by Django 4.2.4 on 2024-05-20 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("music_base", "0007_song_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="descriptions",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="scale",
        ),
        migrations.DeleteModel(
            name="Description",
        ),
        migrations.DeleteModel(
            name="Scale",
        ),
    ]
