# Generated by Django 4.2.4 on 2024-05-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music_base", "0008_remove_song_descriptions_remove_tag_scale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="song_ids_ordered",
            field=models.CharField(default="", max_length=1024),
        ),
    ]
